### ISSUE TITLE
wekan canno't start since upgrade.

### ISSUE THREAD

**Issue by stoutouloutou** [YunoHost-Apps/wekan_ynh#117]
Hello,
Wekan refuses to start since I upgraded to version 5.17~ynh1 from the UI : the wekan service try restarting forever, here are the logs :

```
avril 27 07:06:13 systemd[1]: Started Wekan, task board.

avril 27 07:06:13 systemd[1943]: wekan.service: Changing to the requested working directory failed: Permission denied

avril 27 07:06:13 systemd[1943]: wekan.service: Failed at step CHDIR spawning /opt/node_n/n/versions/node/12.16.3/bin/node: Permission denied

avril 27 07:06:13 systemd[1]: wekan.service: Main process exited, code=exited, status=200/CHDIR

avril 27 07:06:13 systemd[1]: wekan.service: Failed with result 'exit-code'.

avril 27 07:06:23 systemd[1]: wekan.service: Service RestartSec=10s expired, scheduling restart.

avril 27 07:06:23 systemd[1]: wekan.service: Scheduled restart job, restart counter is at 69.

avril 27 07:06:23 systemd[1]: Stopped Wekan, task board.
```
(Yunohost up to date 4.1.8 stable, I tried restarting it, didn't change anything)

Thank you for your help !

**Comment by yalh76** [comment]
I've tested two times without having that issue.

do you know how to connect from the command line ? to check rights on the wekan folder and on `/opt/node_n/n/versions/node/12.16.3/bin/node`

**Comment by yalh76** [comment]
can you also check the rights for the folder `/var/www/wekan`

**Comment by stoutouloutou** [comment]
yep ! 
the wekan folder: 
`drwxr-x--- 4 wekan    wekan    4096 Apr 26 07:25 wekan`

**Comment by stoutouloutou** [comment]
I don't know if it's a problem, but I don't see any wekan user in /etc/passwd.
(i tried to uninstall  wekan, it said :
```
Warning: userdel: cannot remove entry 'wekan' from /etc/passwd
Warning: /usr/sbin/deluser: `/usr/sbin/userdel wekan' returned error code 1. Exiting.
Warning: /usr/sbin/delgroup: `wekan' still has `wekan' as their primary group!
```
)

**Comment by yalh76** [comment]
Maybe you had an issue on your YunoHost, because during upgrade wekan user is not deleted ...

**Comment by stoutouloutou** [comment]
I deleted a "wekan" user from the interface (ldap), reinstall, and it worked !

**Comment by stoutouloutou** [comment]
(I think I created this user a long time ago)
