### ISSUE TITLE
The smtp configuration parameters in the admin are gone after upgrading to 5.17.0

### ISSUE THREAD

**Issue by SiM** [YunoHost-Apps/wekan_ynh#118]
### Describe the bug

In the Wekan admin panel, email tab, there is now only the "_Send a test email to yourself_" button.
There are no more configuration fields.

Inspecting html with developper toolbar, I see that there is commented code, which starts with `<!--if isSandstorm-->` 

I have the problem on two different instances upgraded to 5.17.0 (yunohost 4.1.8)
The problem is not present in 5.00.0

**Comment by SiM** [comment]
After more search, I found that since 5.02 there is no email settings at Admin Panel anymore. (cf. https://github.com/wekan/wekan/wiki/Troubleshooting-Mail)

According to the link above, the mail configuration is done by settings of `MAIL_URL` & `MAIL_FROM` environment parameters.
How to do that in YNH context?

**Comment by inrepublica** [comment]
Same problem for me...

**Comment by yalh76** [comment]
Have you checked on last wekan version ?
