### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by trillerpfeife** [YunoHost-Apps/wekan_ynh#131]
### Describe the bug

Installation failed. 

Note: Before I upgraded Yunohost to the next Version Wekan was working perfectly fine. It stopped working after the upgrade!

### Context

- Hardware: VPS 
- YunoHost version: 4.2.6.1
- I have access to my server: Through SSH | through the webadmin
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no
- Using, or trying to install package version/branch: 5.35~ynh1

### Logs

You will find the complete log here: https://paste.yunohost.org/raw/pagusaruxi

**Comment by yalh76** [comment]
Seems that mongodb service didn't started, maybe you should try to reinstall it, just to be sure it's not a one time error

**Comment by trillerpfeife** [comment]
I tried to reinstall it before I removed mongodb
sudo yunohost service remove mongodb

this is my Log: https://paste.yunohost.org/raw/azofuqitok

**Comment by yalh76** [comment]
can you try to install last version ?
