### ISSUE TITLE
Installation impossible sur Raspberry Pi 4 8G, avec version Raspbian 64bit

### ISSUE THREAD

**Issue by donanjo** [YunoHost-Apps/wekan_ynh#137]
Matériel : Raspberry PI 4 8G
Version Yunohost : 4.3.6.2
Version Raspbian : 2021-05-07-raspios-buster-arm64-lite

https://paste.yunohost.org/raw/exuveziyaf

**Comment by nanro22** [comment]
Hi, I have exactly the same issue with the same material. In log, that talk about mongodb-org, mongodb-org-server and mongodb-org-tools with that : 
is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or is only available from another source

**Comment by yalh76** [comment]
if you can access your sever though SSH, can you provide the result of `dpkg --print-architecture` and `lscpu`

**Comment by donanjo** [comment]
Résultat dpkg --print-architecture : arm64
Résultat lscpu ;=:
Architecture:        aarch64
Byte Order:          Little Endian
CPU(s):              4
On-line CPU(s) list: 0-3
Thread(s) per core:  1
Core(s) per socket:  4
Socket(s):           1
Vendor ID:           ARM
Model:               3
Model name:          Cortex-A72
Stepping:            r0p3
CPU max MHz:         1500.0000
CPU min MHz:         600.0000
BogoMIPS:            108.00
Flags:               fp asimd evtstrm crc32 cpuid

**Comment by yalh76** [comment]
mongodb can't be installed on aarch64
