### ISSUE TITLE
Mongodb down ater upgrading wekan app

### ISSUE THREAD

**Issue by innovea32** [YunoHost-Apps/wekan_ynh#138]
Hi,

Mongodb is down ater upgrading wekan app - Apt has installed Mongodb 4.4.12

I have upgraded wekan app and after that I get : "bad gateway" when trying to use app.

The mongodb server is not working.

On the log I can see it is trying to repair itself but failed on : 

WiredTiger bad version (before it tries to repair database).

Due to multiples retries, log is using a lot of disk space.

What should I do to recover data and a working app ?

Thanks for your help

**Comment by yalh76** [comment]
I have the same issue on my own instance, but unable to reproduce for now, when restoring the backup on another yunohost, I was able to upgrade without any issue ...

**Comment by ebouaziz** [comment]
There is another issue with mongodb that happened recently : MongoDB 5 on x86 now requires AVX instructions. Many of us run Yunohhost on salvaged hardware that does not have these instructions, triggering this king of errors :
`traps: mongod[16491] trap invalid opcode ip:[...]`
I'm looking for a way to downgrade now.

**Comment by innovea32** [comment]
I have tried to downgrade mongo db and reload ynh backup (command line).

After several failures, it seams to word again.

Mongodb cannot repair database after upgrade. (In my case this is a VPS, so I don't understand the reason why database needs to be repaired).

Issues also seams to be generated by a change in mongodb package name (mongo / mongodb)

**Comment by ebouaziz** [comment]
I managed to restore the backup by changing the mongodb-org version to 4.4 in `apps/wekan/settings/scripts/ynh_mongo_db__2` in the `/home/yunohost.backup/archives/wekan-pre-upgrade1.tar`.

**Comment by SiM** [comment]
> I managed to restore the backup by changing the mongodb-org version to 4.4 in `apps/wekan/settings/scripts/ynh_mongo_db__2` in `/home/yunohost.backup/archives/wekan-pre-upgrade1.tar`.

How did you do @ebouaziz ?

I try changing MONGO_CE_REPO and MONGO_CE_KEY from 5.0 to 4.4 but it didn't worked

**Comment by yalh76** [comment]
You can upgrade to last version, it's back on mongodb 4.4
