### ISSUE TITLE
GUI is down after wekan upgrade

### ISSUE THREAD

**Issue by dev-emre-yildiz** [YunoHost-Apps/wekan_ynh#147]
Hi,
After the wekan upgrade on yunohost server last week, my gui is not properly working. 

![image](https://user-images.githubusercontent.com/97280123/172042795-b2c7d9ec-3bcf-4ed9-b458-e40a4d374189.png)

**Comment by menestrwell** [comment]
The same here

Actually I have too much recurtion error in my web browser console
![Capture d'écran Deepin_zone de sélection _20220606172801](https://user-images.githubusercontent.com/75116332/172192821-15e39fc3-70f5-4f85-8adf-e0e4cc115460.png)

**Comment by Tagadda** [comment]
Hi. Can you share the upgrade logs with YunoPaste, from the web admin ?

**Comment by menestrwell** [comment]
Yesss :)

https://paste.yunohost.org/raw/ufilinuvif

**Comment by yalh76** [comment]
Seems like an issue on upstream : https://github.com/wekan/wekan/issues/4545 should be fixed at next version: v6.28

**Comment by menestrwell** [comment]
Thanks

**Comment by dev-emre-yildiz** [comment]
it's working. thanks.
