### ISSUE TITLE
Wekan Ldap Users Vs Password User Permissions

### ISSUE THREAD

**Issue by P4ul2000** [YunoHost-Apps/wekan_ynh#164]
Hi,

I have Wekan 6.30.0 installed and finding that a user with a Yunohost account can create and use Templates, but if a user account is created directly with Wekan and a password is used to sign in in place of Ldap templates can not be used. Is there a way Wekan user accounts created with a password and that do not have a yunohost account can be given permission you use templates please? 

Thank you!

**Comment by yalh76** [comment]
you should look at wekan for the roles availables
