### ISSUE TITLE
Version 1.00 released!

### ISSUE THREAD

**Issue by JimboJoe** [YunoHost-Apps/wekan_ynh#17]
https://blog.wekan.team/2018/05/wekan-v1-00-released/index.html :tada:

**Comment by alexAubin** [comment]
Woot :O

**Comment by alexAubin** [comment]
For christ sake, https://releases.wekan.team/wekan-0.89.tar.gz disappeared -_-

**Comment by zamentur** [comment]
I made the update here https://github.com/YunoHost-Apps/wekan_ynh/pull/18
