### ISSUE TITLE
ROOT_URL is set to dev value in systemd file, that break clicking on a card

### ISSUE THREAD

**Issue by Psycojoker** [YunoHost-Apps/wekan_ynh#2]
Hello,

In https://github.com/YunoHost-Apps/wekan_ynh/blob/master/conf/systemd.service#L14 the `ROOT_URL` value is set for a value used for developing on local host, this mean that when you click on a card in a column you are redirected to local host and you can play with it.

     Environment=ROOT_URL=http://127.0.0.1:__PORT____URI__ PORT=__PORT__

In production, for YunoHost, I had to change it to the real domain like that:

    Environment=ROOT_URL=https://wekan.yunohost.org/ PORT=8081

**Comment by alexAubin** [comment]
That should be easy to fix, but needs to be tested just to be sure : 

Probably add a line like this around [here](https://github.com/YunoHost-Apps/wekan_ynh/blob/master/scripts/install#L103) : 

```
ynh_replace_string "__DOMAIN__" "$domain" "../conf/systemd.service"
```

and in  the systemd conf, have : 

```
Environment=ROOT_URL=https://__DOMAIN__:__PORT____URI__ PORT=__PORT__
```

(note the http**s** as mentionned by Bram)

Should also be tested for subpaths (i.e. URI = /toto)

**Comment by zamentur** [comment]
Fixed with https://github.com/YunoHost-Apps/wekan_ynh/commit/28afa51fd8d507f7aa308ac0f5e2dd25d8452210
