### ISSUE TITLE
Your app is broken

### ISSUE THREAD

**Issue by maniackcrudelis** [YunoHost-Apps/wekan_ynh#24]
Hello

Your app is failing on our CI
https://ci-apps.yunohost.org/ci/job/127

Please try to fix this app before Sunday 21th, otherwise it will be set at notworking.
If you need help, don't hesitate to ask on our chat rooms,
- IRC: #yunohost-apps on irc.freenode.net
- Matrix: #freenode_#yunohost-apps:matrix.org
- XMPP: apps@conference.yunohost.org

**Comment by alexAubin** [comment]
Henlow,

https://github.com/YunoHost-Apps/wekan_ynh/pull/23 should fix this !

**Comment by maniackcrudelis** [comment]
Looks like it's not enough
https://ci-apps.yunohost.org/ci/job/712

**Comment by alexAubin** [comment]
Eeeeeh I can't reproduce the issue D: 

```
Warning: yunohost.hook <lambda> - [930.1] E: The repository 'http://httpredir.debian.org/debian stretch Release' does no longer have a Release file.
Warning: yunohost.hook <lambda> - [930.1] E: Failed to fetch http://cdn-fastly.deb.debian.org/debian/pool/main/p/pcre3/libpcrecpp0v5_8.39-3_amd64.deb  404  Not Found [IP: 151.101.112.204 80]
```

This looks like a temporary network issue on the CI ? :s

**Comment by maniackcrudelis** [comment]
https://ci-apps.yunohost.org/ci/job/720
Wait and see...

**Comment by alexAubin** [comment]
App is now level 3
