### ISSUE TITLE
Upgrade to latest version

### ISSUE THREAD

**Issue by JimboJoe** [YunoHost-Apps/wekan_ynh#25]
Upstream development seems to be [going fast](https://github.com/wekan/wekan/blob/devel/CHANGELOG.md)!
Currently 1.95 version is available, including official LDAP support :blush:

**Comment by yalh76** [comment]
push to 2.42 in https://github.com/YunoHost-Apps/wekan_ynh/pull/34 if you want to review ;)

**Comment by fflorent** [comment]
Seems like we are in version > 2.5 now, can't this issue be closed? :)

Florent

**Comment by alexAubin** [comment]
Indeed, cheers :wink:
