### ISSUE TITLE
WeKan 7.02

### ISSUE THREAD

**Issue by xet7** [YunoHost-Apps/wekan_ynh#259]
Hi,
@intellekta asked about this bug https://github.com/wekan/wekan/issues/5034 that is now fixed in WeKan v7.02.
You can upgrade yunohost to WeKan v7.02.
Thanks!

BR,
xet7
Maintainer of WeKan

**Comment by xet7** [comment]
Release notes: https://github.com/wekan/wekan/releases/tag/v7.02

Newest Node.js: https://github.com/wekan/node-v14-esm/releases/tag/v14.21.4

**Comment by intellekta** [comment]
wow, thank you.
