### ISSUE TITLE
Export does not work anymore in 2.09

### ISSUE THREAD

**Issue by authago** [YunoHost-Apps/wekan_ynh#33]
Thanks for the updates, much appreciated!

Export does not seem to work anymore in my installation of 2.09.
It's an api call and it directly reverts me to the Yunohost user login/landing page without visible error.

Tried:
- powercycle
- update Yunohost
- remove/install Wekan, exporting Welcome board
- scanning /var/log for clues, none found yet

**Comment by alexAubin** [comment]
Uuuuh, what do you mean by "export" ?

**Comment by authago** [comment]
Ah, to export a board via the user interface:
Open board -> Hamburger menu top right -> Export Board.

**Comment by arthurlogilab** [comment]
Same here, I get redirected to yunohost login page

**Comment by authago** [comment]
Works in 2.56! (now in testing branch)

**Comment by arthurlogilab** [comment]
Looking forward to test this fix, @authago any chance of pushing that testing branch ? (probably related to #42 )

**Comment by yalh76** [comment]
As we are now in 2.98, exports work.
Issue can be closed

**Comment by arthurlogilab** [comment]
Works for me. Thanks !
