### ISSUE TITLE
Patch with ldap support

### ISSUE THREAD

**Issue by zamentur** [YunoHost-Apps/wekan_ynh#4]
Wekan doesn't seem to support officially ldap.

But we can found patch to do it in the cloudron package https://git.cloudron.io/cloudron/wekan-app/blob/master/Dockerfile

**Comment by zamentur** [comment]
The issues is in this case we are obliged to compile js with meteor and there is a lot resources used in this operations (not good for arm support).

It seems there are 3 choices:

- Keep disconnected from ldap and be able to setup on arm
- apply the cloudron patches and uses meteor (so put this app imcompatible with small arm board)
- precompile with meteor patches from cloudron and host them (automatically?)

**Comment by alexAubin** [comment]
Just my opinion on this, but we should definitely seek compatibility with ARM ~and~ LDAP support...

So the third option is the one that sounds good/acceptable to me, though it does require some work to automate this process and find a place to host this (but then we have other apps with similar issue, i.e. the upstream archive disappears, which is also a problem here (c.f. #12))

**Comment by arthurlogilab** [comment]
New documentation : https://github.com/wekan/wekan/wiki/LDAP

**Comment by yalh76** [comment]
Ldap integrated in https://github.com/YunoHost-Apps/wekan_ynh/pull/34, if you want to review

**Comment by decentral1se** [comment]
This should be closed? As far as I understand, LDAP support is working.

**Comment by yalh76** [comment]
> 
> 
> This should be closed? As far as I understand, LDAP support is working.

Yes it can be closed, LDAP support is working :)

**Comment by alexAubin** [comment]
Cheers !
