### ISSUE TITLE
forgot-password URL is not relative

### ISSUE THREAD

**Issue by arthurlogilab** [YunoHost-Apps/wekan_ynh#41]
When installing wekan-ynh in a "folder" https://y.example.org/wekan/ the link generated for "forgot my password" is https://y.example.org/forgot-password ... it should be https://y.example.org/wekan/forgot-password (typing that URL seems to work)

**Comment by yalh76** [comment]
Is it still the case with the last version: 2.98

**Comment by yalh76** [comment]
Feel free to reopen this issue if needed.
