### ISSUE TITLE
Page keeps reloading

### ISSUE THREAD

**Issue by jlnbdt** [YunoHost-Apps/wekan_ynh#49]
Hi,

I would like to post here a [message](https://forum.yunohost.org/t/wekan-packaging/2468/7?u=jln) I left on the Yunohost forum.

Since the last update, I’ve a “connection” problem. The page keeps reloading as you can see here: https://10qt.net/jirafeau/f.php?h=2t7T0DyP

Thanks a lot!

**Comment by yalh76** [comment]
can you try to upgrade to the last version using `yunohost app upgrade wekan` and let us know if it solve the problem

**Comment by jlnbdt** [comment]
Hi,

Yes, the problem is solved! :+1: 

Thanks!

**Comment by jlnbdt** [comment]
I spoke too quickly: the problem always occurs on one of my machines.

**Comment by yalh76** [comment]
Can you check the content of /var/www/wekan/.env if there is variables using __ not replaced during the upgrade

**Comment by jlnbdt** [comment]
I can’t find any string with __ in it in that file.

**Comment by yalh76** [comment]
and do you see any differences between the .env files of both machines ?

**Comment by jlnbdt** [comment]
When I wrote "machines", I meant to say "desktop computers".
My install is a public one, in order to easily use Wekan API.

**Comment by yalh76** [comment]
But you said : `the problem always occurs on one of my machines.`
This means, it work on another machine or I misunderstand you ?

**Comment by jlnbdt** [comment]
You understand correctly.

I thought the problem was solved after trying with my personal computer. But with my professional computer, the problem persists (I have disconnected and reconnected). I can temporarily redo the update to refine the diagnosis if necessary.

**Comment by yalh76** [comment]
You try to connect to the same wekan instance from your personal computer and professional computer or you have a wekan installed on your personal computer and another one installed on your professional computer?

**Comment by jlnbdt** [comment]
I try to connect to the same wekan instance (hosted an a Kimsufi VPS) from my professional and personal computers.

**Comment by yalh76** [comment]
Can you try to remove cookies and cache on your professional computer ? To let see if it solves the issue

**Comment by jlnbdt** [comment]
It doesn't solve the issue. More precisely, it fixes the problem for a time, but it reappears:

- being on the main interface of Yunohost, I click on Wekan. I am then confronted with the problem.
- I delete all my cookies, I reconnect (through the Yunohost interface, then the Wekan interface): the problem disappears
- then I come back (in the same tab) to the main interface of Yunohost, and then restart Wekan. The problem reappears.

I would like to mention three more things:
- after several tests, the problem is the same on both my computers (the professional one and the personal one), not only on the professional
- Wekan is not installed in a subdomain, but in a subfolder of the main domain (Would you like me to try to install wekan on a subdomain?)
- I had [some warnings](https://10qt.net/zerobin/?98845e7f7fa3e1b8#2SshaZe0cNVX3o4tZre9A5PWLSLosh/KGsCM1QWq1uo=) at the update

**Comment by yalh76** [comment]
Seems related to https://github.com/YunoHost/issues/issues/1420

**Comment by jlnbdt** [comment]
Seems resolved with the last update. Thanks :)
