### ISSUE TITLE
starring boards and swimlanes not possible

### ISSUE THREAD

**Issue by novadeviator** [YunoHost-Apps/wekan_ynh#51]
It is not possible to star a board - UI quickly jumps from star on to star off again. 

Similarly when in the board, when you click  on icon that says 'Lists', it jumps to 'Swimlanes' for a second (and swimlanes appear), but in a split second it jumps back to Lists and swimlanes dissapear from board.

I'm not sure, but I have a weird feeling this is connected to expired session at https://github.com/YunoHost-Apps/bitwarden_ynh/issues/3 - does the JS/CSS from the ynh overlay conflicting with something?

**Comment by novadeviator** [comment]
I can confirm that if I installed Wekan with 'public service' on, and logged into it while **logged out** from YNH - so there was no overlay - starring was working and it was possible to create swimlanes.

**Comment by chavlu** [comment]
hi, I can confirm the behaviour for swimlanes : no matter for those who are admin of the wekan instance, but not visible for all others, even if admin of the board

**Comment by dosch** [comment]
I can confirm, but only partly.
My useraccount has no issues with this ( I am admin). But a newly created account can has this same issue.

It also has the issue that it can't accept invites to shared boards. This issue looks similiar in behavior as the button also quickly blink to accepted and then back, just like @novadeviator  said about the star.

**Comment by yalh76** [comment]
Did we know if it's related to YunoHost or the 2.98 version used?

**Comment by dosch** [comment]
I no longer experience this bug since the upgrade to 3.45
