### ISSUE TITLE
Yunohost SSO not used

### ISSUE THREAD

**Issue by dosch** [YunoHost-Apps/wekan_ynh#52]
The existing Yunohost users do no automatically have access to the Wekan.
Users need to be invited anew into Wekan.

**Comment by yalh76** [comment]
Just tested, and all yunohost users have access to wekan automatically choosing LDAP as authentication method

**Comment by dosch** [comment]
my username on wekan is identitcal to the one used on yunohost.
I set LDAP as authentication method in the admin section.

But I still get the wekan login screen after I already logged in to yunohost.
Am I missing something?

**Comment by yalh76** [comment]
no, SSO / Single Sign On is still not implemented

**Comment by dosch** [comment]
ok, I am not sure what I don't understand... but could it be that:

1. SSO is not enabled: so you need to login twice. (one for YNH and once for WeKan
2. But any user of YNH can use the same name and password if LDAP is turned on for that user.

Is this correct?

**Comment by yalh76** [comment]
It’s correct, you have understood
