### ISSUE TITLE
Current version is v3.25 2019-08-23

### ISSUE THREAD

**Issue by dosch** [YunoHost-Apps/wekan_ynh#54]
The current version is [v3.25 2019-08-23](https://github.com/wekan/wekan/blob/master/CHANGELOG.md#v325-2019-08-23-wekan-release)

Is there a change the YNH version will get this upgrade?

**Comment by anmol26s** [comment]
@yalh76 will you update the package?

**Comment by dosch** [comment]
@anmol26s if I look at @yalh76 profile it seems that he either is on a very long holiday, or that he quit github. I hope nothing worse then that has happened...

**Comment by alexAubin** [comment]
@dosch Thanks for caring <3 I believe he just started a new job and has less time to contribute unfortunately :[

**Comment by dosch** [comment]
thnx for letting us know. A great loss for the movement. Damn those paid jobs 👿
(just kidding, if you read this @yalh76 congrats on finding a nice position!)

**Comment by dosch** [comment]
@alexAubin and @anmol26s can I maybe help you in some way to get Kimai updated? I'd be happy to sponsor you in some way...

**Comment by yalh76** [comment]
Hi :)

I'm back there. I was just away from coding, new job, bit tired and bored of coding bugs ^^

For wekan, the point is: 
- there are too much releases... https://github.com/wekan/wekan/releases 
- sometimes there are few changes from one release to another one
- v3.0 is not a big change in not a big change from 2.99, it's like a +0.01 from 2.99
- wekan_ynh also provide an arm64 build, so we need to have a build available at https://releases.wekan.team/raspi3/ or build one....
- building a release need time and skills that are just around my competencies limits

The point that would really help us to have wekan_ynh up to date:
- having wekan with less releases,
- each release more atomic, like representing something coherent
- each one with a description of fixes and improvements (an example to let you compare : https://github.com/pixelfed/pixelfed/releases)
- each one provided with an amd64 and an arm64 build

BTW: Wekan is awesome, I use it a lot, it manage my YunoHost todo list and I won't be able to package YunoHost apps without it:
![image](https://user-images.githubusercontent.com/30271971/66007327-366dfc00-e4b2-11e9-83fb-699d7080c9df.png)

So a big thank you for what has already be done.
But packaging it and maintaining it up to date is a marathon. So the most helpfull for us would be that you find a way to help wekan developpers to improve their coding project management skills :)

**Comment by dosch** [comment]
Thank you @yalh76 for your elaborate answer! (and welcome back). 
I understand what you mean... If alright with you, I will forward these comments also to the wekan team as I think they are very reasonable.

For me the main reason I keep coming back to this is that I want Wekan to be just as usefull to me as it is to you. But one essential thing that does not work for me is [sharing boards with team members.](https://github.com/YunoHost-Apps/wekan_ynh/issues/55). I was hoping that an update to the latest version might solve this... But seeing the (complete) lack of release notes.. this is not even certain. And maybe it is a YNH bug to start with... 

Thank you for your work so far and I hope Wekan can indeed improve as a project so it becomes easier for the YNH peeps to include it.

**Comment by dosch** [comment]
@yalh76 a teammember from wekan picked up on your topics here on their forum. You can [read them here.](https://community.vanila.io/wekan/general/wekan-and-yunohost~8241c027-f39e-44b3-ab19-15df7a61039e)
Hope this helps!

**Comment by yalh76** [comment]
> 
> 
> @yalh76 a teammember from wekan picked up on your topics here on their forum. You can [read them here.](https://community.vanila.io/wekan/general/wekan-and-yunohost~8241c027-f39e-44b3-ab19-15df7a61039e)
> Hope this helps!
lol he is not a teammember for wekan, he's the main maintainer since 2 years ^^
