### ISSUE TITLE
Slow-down and excessive memory and CPU usage

### ISSUE THREAD

**Issue by carinedengler** [YunoHost-Apps/wekan_ynh#59]
Wekan is slowing down after a certain amount of run time (order days to few weeks) to the point that it cannot be used at all; this issue can be temporarily resolved by restarting it. The problem seems to be caused by Node.js filling up the memory and using the CPU to full capacity.

Version 2.98~ynh1

**Comment by yalh76** [comment]
Have you tried to upgrade to 3.45 ?

**Comment by carinedengler** [comment]
Following your suggestion, we upgraded some time ago (~1 week) - until now the problem has not resurfaced. Given that the problem usually showed itself after days to a few weeks, I'll close the issue if it has not reoccurred until the end of November. Thank you for your help (and your project of course)!

**Comment by carinedengler** [comment]
As of today the problem has not reoccurred, thanks again for your help!
