### ISSUE TITLE
Email function not working

### ISSUE THREAD

**Issue by dosch** [YunoHost-Apps/wekan_ynh#60]
I checked and cross-checked my email settings, but sending email is not working. 

When I try to send a testmail from the admin panel I get:

`Sending email failed
Error trying to send email: 140319669086016:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:827:`

I use port 587 and have TLS support enabled

**Comment by yalh76** [comment]
Have you tried disabling TLS support ?

**Comment by yalh76** [comment]
Without news, I close that issue. Feel free to reopen that issue

**Comment by dosch** [comment]
@yalh76 sorry for the silence. I was unable to test this for a very silly reason; I can no longer access the admin settings... I seem to have somehow downgraded my account to the level of a simple user 😄 
thnx for the recent update and the continued support for this package btw

**Comment by yalh76** [comment]
ok..; then maybe the mail issue will be solved with https://github.com/YunoHost/yunohost/pull/882

**Comment by dosch** [comment]
Any change you have a tip to regain admin privs.? Or shall I open a separate ticket for that?

**Comment by yalh76** [comment]
maybe : https://github.com/YunoHost-Apps/wekan_ynh/blob/7c585b555385c33a49e61407fcea37812849d88d/README.md#L31-L35

Something related to ldap authentication...

**Comment by zamentur** [comment]
To fix that i have set this settings:
Host: the main domain (localhost doesn't work)
Port: 25
TLS: no
User: a user on yunohost with mail permission
Password:  user's password
From: the email of this user

TLS with 587 didn't work indeed.

I tested it in yunohost 3.7

**Comment by yalh76** [comment]
> 
> 
> To fix that i have set this settings:
> Host: the main domain (localhost doesn't work)
> Port: 25
> TLS: no
> User: a user on yunohost with mail permission
> Password: user's password
> From: the email of this user
> 
> TLS with 587 didn't work indeed.
> 
> I tested it in yunohost 3.7

Yes it's a good way to solve that issue. the other I have to test it is https://github.com/YunoHost/yunohost/pull/882

**Comment by yalh76** [comment]
now solved
