### ISSUE TITLE
Backup backups the source code

### ISSUE THREAD

**Issue by thomasstauffer666** [YunoHost-Apps/wekan_ynh#70]
At the moment a backup is > 200 MB, even if there is no board. Is this intentionally done? If not, I may also look into the issue.

**Comment by yalh76** [comment]
just tested and the .tar.gz backup file is more: 85 Mo...

And the [source file for wekan](https://build.yunohost.org/apps/wekan-3.55.zip) is: 99 Mo

So the only thing I could say is: good job tar and gzip
