### ISSUE TITLE
Backup backups the source code

### ISSUE THREAD

**Issue by thomasstauffer666** [YunoHost-Apps/wekan_ynh#71]
Sorry that I recreate the question (#70), because you already closed it I had no chance to clarify my question. For me this is still unanswered. As written previously

When I do a backup on an freshly installed Wekan app my backup just of Wekan is 200 MB. I could send a link to my installation with a username/password to check this. But even if it is only is 90 MB or 88 MB.

My question is: Why is the source code in the backup? When I open then backup manually and remove the source code manually the backup is < 1 MB. For me this looks like a unexpected behavior in the backup script? Is there a reason for it?

**Comment by yalh76** [comment]
It's the way YunoHost manage backup. It do a full backup of the source full + datas to be able to reinstall it completly on the same YunoHost or another YunoHost.

All backup script for all YunoHost packages are made like that.

PS: even closed, you can add comment to an issue and repoen it

**Comment by thomasstauffer666** [comment]
Ok, thanks for the information I didn't realize this (the other things are too small compared to Wekan). Thanks for the heads up.
