### ISSUE TITLE
mongodb service remains after uninstall

### ISSUE THREAD

**Issue by scharc** [YunoHost-Apps/wekan_ynh#73]
I tried wekan for a couple of weeks and decided to move on and uninstall it. Since then mongodb service remains in the service overview as 
> Status: unknown
Started at unknown

**Comment by yalh76** [comment]
Yes, that's normal... It's related to https://github.com/YunoHost-Apps/wekan_ynh/issues/14

We can't remove it from the service list, as we don't know if it's not used by other apps...

But you can remove it manually doing : `yunohost service remove mongodb`
