### ISSUE TITLE
Problemes connecting issues

### ISSUE THREAD

**Issue by yoyomimo** [YunoHost-Apps/wekan_ynh#81]
I make a video it will be easier for make me anderstand

https://vimeo.com/401608976/07dadaefd7

Thank You :)

**Comment by SiM** [comment]
Same problem here on a fresh wekan install : impossible to log in.

**Comment by SiM** [comment]
Problem solved with latest upgrade

**Comment by yoyomimo** [comment]
Thanks, do I need to close the topic on GitHub?
