### ISSUE TITLE
Cards link to 127.0.0.1:8081

### ISSUE THREAD

**Issue by raphaeljolivet** [YunoHost-Apps/wekan_ynh#9]
Hi, 

I just installed Wekan on my Yunohost, using this git repo (latest master).
It installs fine, but when I click any card, it links to local URLs  like : http://127.0.0.1:8081/wekan/b/nrBBQrQob9Jh7Lar7/test-board/8QsYAGbuJ7yDDg2NQ

Do you have any idea what could be wrong ?

**Comment by alexAubin** [comment]
We just merged the testing branch, which should include a fix for this :+1: 

Feel free to re-open if you re--experience this bug :+1:

**Comment by raphaeljolivet** [comment]
Works like a charm 👌
