### ISSUE TITLE
Wrong email address, cannot change 

### ISSUE THREAD

**Issue by kuba-orlik** [YunoHost-Apps/wekan_ynh#93]
I've logged in over LDAP to a ynh version of Wekan. Upon login, I've realized that my email address is wrong - set to "undefined" domain: 

![image](https://user-images.githubusercontent.com/2697916/84303821-1d404380-ab47-11ea-9444-cde203888520.png)

I've tried enabling "Allow email change" in the admin settings:

![image](https://user-images.githubusercontent.com/2697916/84303865-33e69a80-ab47-11ea-9955-297a8ed3fa2a.png)

But I can't still edit my email. This is also true for non-ldap accounts.

**Comment by fflorent** [comment]
Same issue here.

**Comment by fflorent** [comment]
I wonder if that may not be due to this issue:
https://github.com/wekan/wekan-ldap/issues/57

I have several mail adresses for my main user but other users don't and have their email correctly set.

**Comment by kuba-orlik** [comment]
I also have several mail addresses for my user :thinking:

**Comment by fflorent** [comment]
I think I got a workaround or even a fix.

I don't warranty about the result. YOU MAY DO A BACKUP BEFORE FOLLOWING THESE STEPS.

In `/var/www/wekan/.env`, change this:

```diff
 # LDAP_DEFAULT_DOMAIN : The default domain of the ldap it is used to create email if the field is not map correctly with the LDAP_SYNC_USER_DATA_FIELDMAP
 # example :
 #LDAP_DEFAULT_DOMAIN=
+LDAP_DEFAULT_DOMAIN=<YOURDOMAIN.TLD>
```

Then you'll have to purge all users in mongo:

```bash
$ mongo
> use wekan
> db.users.find({authenticationMethod: "ldap"})
```

Check that all users are ones from ldap and then

```bash
> db.users.deleteMany({authenticationMethod: "ldap"})
> quit()
```

Then restart wekan:
```bash
> sudo systemctl restart wekan.service
```

Login again using your LDAP account and that should fix your email address.

Hope to help! Feedback welcome :-)

**Comment by yalh76** [comment]
Have you tested with last wekan version?
