### ISSUE TITLE
Cannot test SMTP connection

### ISSUE THREAD

**Issue by fflorent** [YunoHost-Apps/wekan_ynh#96]
Just referencing an issue that has been fixed upstream in case other people meet it.

We cannot test SMTP connection though the admin panel.

The fix is here:
https://github.com/wekan/wekan/commit/afcb8aa49b254fc686f55c5f094b5ee2ac50ebf9

Dirty workaround: modify `/var/www/wekan/programs/server/app/app.js:15072` with:
```diff
-      if (!user.emails || !user.emails[0] || user.emails[0].address) {
+      if (!user.emails || !user.emails[0] || !user.emails[0].address) {
```

And restart wekan.

That should work now.

Don't hesitate to close the issue if you feel it is irrelevant, I won't bother :).

**Comment by kuba-orlik** [comment]
That worked for me, thanks!
